### ISSUE TITLE
Можешь вести систему контроля обновлений?

### ISSUE THREAD

**Issue by Mrrebrik-code** [Ma0oo/Instruments_Pack2#1]
Я имею введу по поводу вех и создать проект для данного репозитория. Мне кажется будет удобно следить за всеми обновлениям и тем, что планируется добавиться и понимать что сейчас допустим разрабатывается.

Удобные инструменты у гитхаба для ведения проекта на самом деле :)

**Comment by Ma0oo** [comment]
Смотри. У меня это гитхаб сборник всех систем, которые я написал в свое время и переписывать на новом проекте очень не хочу. Так что системы здесь будут появляться и исчезать. Оставаться будут те, которые хорошо себя зарекомендовали, b если система оказалась не очень или вообще разовая - то в мусорку её.

В [ReadMe.txt в корневой папке](https://github.com/Ma0oo/Instruments_Pack2)/README.txt - можешь почитать что такое система в данном репозитории.

Насчёт проекта: меня ждёт [джем](https://itch.io/jam/revival-jam-2). Проекта с этого джема выложу в открытый доступ, как пример использования репозитория.

P.s. Сейчас прилетит новый релиз в unitypackage
